### ISSUE TITLE
npm build failed with nodejs >=12

### ISSUE THREAD

**Issue by nuts424** [risacher/tty.js#14]
Hi,
ttyx seems not compatible to nodejs >= v12:

```
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5

```
and drops errors:
```
/home/nuts/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
  311 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
make: *** [binding.target.mk:105: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/nuts/ttyx/node_modules/ref/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.44-gentoo
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nuts/ttyx/node_modules/ref
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by risacher** [comment]
Working with node 20, so closing this.  'ref' and 'ffi' were problematic and are no longer needed.
